$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: example-azureml-2
version: 1
docker:
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: file:conda/conda.yml
description: Example AzureML2 basic environment example
