dependencies:
  - python=3.6.2
  - scikit-learn
  - numpy
  - pandas
  - pip:
    - azureml-model-management-sdk
    - azureml-defaults
    - azureml-opendatasets
    - inference-schema[numpy-support]
